server:
  servlet:
    context-path: /comp208-group60

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/COMP208-database?characterEncoding=utf-8
    username: root
    password: 171737173Wo01
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:com/group60/mapper/*.xml
  type-aliases-package: com.group60.entity
logging:
  level:
    root: info
    com.group60: debug
